// Banco de Dados de Jogadores Reais para o Brasileirão Série A
export const REAL_PLAYERS = {
  fla: [
    { nome: "Agustín Rossi", posicao: "GOL", idade: 29, forca: 81 },
    { nome: "Matheus Cunha", posicao: "GOL", idade: 24, forca: 73 },
    { nome: "Léo Ortiz", posicao: "DEF", idade: 29, forca: 82 },
    { nome: "Léo Pereira", posicao: "DEF", idade: 30, forca: 80 },
    { nome: "Fabrício Bruno", posicao: "DEF", idade: 30, forca: 79 },
    { nome: "Ayrton Lucas", posicao: "DEF", idade: 28, forca: 78 },
    { nome: "Wesley", posicao: "DEF", idade: 22, forca: 77 },
    { nome: "Alex Sandro", posicao: "DEF", idade: 35, forca: 76 },
    { nome: "Guillermo Varela", posicao: "DEF", idade: 32, forca: 74 },
    { nome: "Giorgian de Arrascaeta", posicao: "MEI", idade: 31, forca: 83 },
    { nome: "Gerson", posicao: "MEI", idade: 28, forca: 82 },
    { nome: "Nicolás de la Cruz", posicao: "MEI", idade: 28, forca: 82 },
    { nome: "Carlos Alcaraz", posicao: "MEI", idade: 23, forca: 78 },
    { nome: "Erick Pulgar", posicao: "MEI", idade: 32, forca: 78 },
    { nome: "Allan", posicao: "MEI", idade: 29, forca: 75 },
    { nome: "Lorran", posicao: "MEI", idade: 19, forca: 71 },
    { nome: "Pedro", posicao: "ATA", idade: 28, forca: 84 },
    { nome: "Everton Cebolinha", posicao: "ATA", idade: 29, forca: 80 },
    { nome: "Luiz Araújo", posicao: "ATA", idade: 29, forca: 79 },
    { nome: "Michael", posicao: "ATA", idade: 29, forca: 78 },
    { nome: "Bruno Henrique", posicao: "ATA", idade: 35, forca: 78 }
  ],
  pal: [
    { nome: "Weverton", posicao: "GOL", idade: 38, forca: 81 },
    { nome: "Marcelo Lomba", posicao: "GOL", idade: 39, forca: 72 },
    { nome: "Gustavo Gómez", posicao: "DEF", idade: 32, forca: 81 },
    { nome: "Murilo", posicao: "DEF", idade: 28, forca: 80 },
    { nome: "Joaquín Piquerez", posicao: "DEF", idade: 27, forca: 79 },
    { nome: "Vitor Reis", posicao: "DEF", idade: 20, forca: 76 },
    { nome: "Marcos Rocha", posicao: "DEF", idade: 37, forca: 75 },
    { nome: "Mayke", posicao: "DEF", idade: 33, forca: 76 },
    { nome: "Caio Paulista", posicao: "DEF", idade: 27, forca: 74 },
    { nome: "Raphael Veiga", posicao: "MEI", idade: 30, forca: 82 },
    { nome: "Aníbal Moreno", posicao: "MEI", idade: 26, forca: 80 },
    { nome: "Maurício", posicao: "MEI", idade: 24, forca: 79 },
    { nome: "Richard Ríos", posicao: "MEI", idade: 25, forca: 78 },
    { nome: "Zé Rafael", posicao: "MEI", idade: 32, forca: 77 },
    { nome: "Gabriel Menino", posicao: "MEI", idade: 25, forca: 75 },
    { nome: "Rômulo", posicao: "MEI", idade: 24, forca: 72 },
    { nome: "Estêvão", posicao: "ATA", idade: 18, forca: 84 },
    { nome: "Felipe Anderson", posicao: "ATA", idade: 32, forca: 80 },
    { nome: "Flaco López", posicao: "ATA", idade: 25, forca: 79 },
    { nome: "Rony", posicao: "ATA", idade: 30, forca: 76 },
    { nome: "Dudu", posicao: "ATA", idade: 34, forca: 77 }
  ],
  bot: [
    { nome: "John", posicao: "GOL", idade: 29, forca: 80 },
    { nome: "Gatito Fernández", posicao: "GOL", idade: 37, forca: 73 },
    { nome: "Bastos", posicao: "DEF", idade: 34, forca: 79 },
    { nome: "Alexander Barboza", posicao: "DEF", idade: 30, forca: 79 },
    { nome: "Adryelson", posicao: "DEF", idade: 27, forca: 78 },
    { nome: "Vitinho", posicao: "DEF", idade: 26, forca: 76 },
    { nome: "Cuiabano", posicao: "DEF", idade: 22, forca: 76 },
    { nome: "Mateo Ponte", posicao: "DEF", idade: 22, forca: 74 },
    { nome: "Marçal", posicao: "DEF", idade: 36, forca: 73 },
    { nome: "Thiago Almada", posicao: "MEI", idade: 24, forca: 83 },
    { nome: "Marlon Freitas", posicao: "MEI", idade: 30, forca: 79 },
    { nome: "Gregore", posicao: "MEI", idade: 31, forca: 78 },
    { nome: "Tchê Tchê", posicao: "MEI", idade: 33, forca: 76 },
    { nome: "Eduardo", posicao: "MEI", idade: 36, forca: 75 },
    { nome: "Allan", posicao: "MEI", idade: 34, forca: 74 },
    { nome: "Kauê", posicao: "MEI", idade: 21, forca: 70 },
    { nome: "Luiz Henrique", posicao: "ATA", idade: 25, forca: 84 },
    { nome: "Igor Jesus", posicao: "ATA", idade: 25, forca: 81 },
    { nome: "Jefferson Savarino", posicao: "ATA", idade: 29, forca: 80 },
    { nome: "Tiquinho Soares", posicao: "ATA", idade: 35, forca: 79 },
    { nome: "Júnior Santos", posicao: "ATA", idade: 31, forca: 78 }
  ],
  sao: [
    { nome: "Rafael", posicao: "GOL", idade: 36, forca: 79 },
    { nome: "Jandrei", posicao: "GOL", idade: 32, forca: 71 },
    { nome: "Robert Arboleda", posicao: "DEF", idade: 34, forca: 80 },
    { nome: "Alan Franco", posicao: "DEF", idade: 29, forca: 78 },
    { nome: "Welington", posicao: "DEF", idade: 25, forca: 76 },
    { nome: "Igor Vinícius", posicao: "DEF", idade: 28, forca: 75 },
    { nome: "Nahuel Ferraresi", posicao: "DEF", idade: 27, forca: 75 },
    { nome: "Rafinha", posicao: "DEF", idade: 40, forca: 74 },
    { nome: "Patryck", posicao: "DEF", idade: 23, forca: 70 },
    { nome: "Lucas Moura", posicao: "MEI", idade: 33, forca: 82 },
    { nome: "Pablo Maia", posicao: "MEI", idade: 24, forca: 79 },
    { nome: "Alisson", posicao: "MEI", idade: 32, forca: 77 },
    { nome: "Luiz Gustavo", posicao: "MEI", idade: 38, forca: 76 },
    { nome: "Rodrigo Nestor", posicao: "MEI", idade: 25, forca: 76 },
    { nome: "Wellington Rato", posicao: "MEI", idade: 33, forca: 75 },
    { nome: "Giuliano Galoppo", posicao: "MEI", idade: 26, forca: 74 },
    { nome: "Jonathan Calleri", posicao: "ATA", idade: 32, forca: 81 },
    { nome: "Luciano", posicao: "ATA", idade: 32, forca: 79 },
    { nome: "Ferreirinha", posicao: "ATA", idade: 28, forca: 78 },
    { nome: "André Silva", posicao: "ATA", idade: 28, forca: 76 },
    { nome: "Erick", posicao: "ATA", idade: 28, forca: 74 }
  ],
  cor: [
    { nome: "Hugo Souza", posicao: "GOL", idade: 27, forca: 78 },
    { nome: "Matheus Donelli", posicao: "GOL", idade: 23, forca: 70 },
    { nome: "André Ramalho", posicao: "DEF", idade: 33, forca: 79 },
    { nome: "Félix Torres", posicao: "DEF", idade: 29, forca: 77 },
    { nome: "Gustavo Henrique", posicao: "DEF", idade: 32, forca: 75 },
    { nome: "Cacá", posicao: "DEF", idade: 26, forca: 76 },
    { nome: "Matheuzinho", posicao: "DEF", idade: 25, forca: 74 },
    { nome: "Matheus Bidu", posicao: "DEF", idade: 26, forca: 74 },
    { nome: "Hugo", posicao: "DEF", idade: 28, forca: 73 },
    { nome: "Rodrigo Garro", posicao: "MEI", idade: 28, forca: 82 },
    { nome: "Breno Bidon", posicao: "MEI", idade: 20, forca: 75 },
    { nome: "André Carrillo", posicao: "MEI", idade: 34, forca: 76 },
    { nome: "Alex Santana", posicao: "MEI", idade: 31, forca: 75 },
    { nome: "Raniele", posicao: "MEI", idade: 29, forca: 75 },
    { nome: "Igor Coronado", posicao: "MEI", idade: 33, forca: 77 },
    { nome: "José Martínez", posicao: "MEI", idade: 31, forca: 75 },
    { nome: "Memphis Depay", posicao: "ATA", idade: 31, forca: 83 },
    { nome: "Yuri Alberto", posicao: "ATA", idade: 24, forca: 80 },
    { nome: "Romero", posicao: "ATA", idade: 33, forca: 76 },
    { nome: "Talles Magno", posicao: "ATA", idade: 23, forca: 77 },
    { nome: "Pedro Raul", posicao: "ATA", idade: 29, forca: 73 }
  ],
  cam: [
    { nome: "Everson", posicao: "GOL", idade: 35, forca: 79 },
    { nome: "Matheus Mendes", posicao: "GOL", idade: 27, forca: 70 },
    { nome: "Junior Alonso", posicao: "DEF", idade: 32, forca: 79 },
    { nome: "Rodrigo Battaglia", posicao: "DEF", idade: 34, forca: 78 },
    { nome: "Lyanco", posicao: "DEF", idade: 29, forca: 76 },
    { nome: "Guilherme Arana", posicao: "DEF", idade: 28, forca: 80 },
    { nome: "Renzo Saravia", posicao: "DEF", idade: 32, forca: 75 },
    { nome: "Igor Rabello", posicao: "DEF", idade: 30, forca: 74 },
    { nome: "Rubens", posicao: "DEF", idade: 24, forca: 73 },
    { nome: "Gustavo Scarpa", posicao: "MEI", idade: 32, forca: 80 },
    { nome: "Matías Zaracho", posicao: "MEI", idade: 27, forca: 79 },
    { nome: "Alan Franco", posicao: "MEI", idade: 27, forca: 77 },
    { nome: "Otávio", posicao: "MEI", idade: 31, forca: 76 },
    { nome: "Fausto Vera", posicao: "MEI", idade: 25, forca: 75 },
    { nome: "Bernard", posicao: "MEI", idade: 33, forca: 75 },
    { nome: "Igor Gomes", posicao: "MEI", idade: 26, forca: 74 },
    { nome: "Hulk", posicao: "ATA", idade: 39, forca: 83 },
    { nome: "Paulinho", posicao: "ATA", idade: 25, forca: 81 },
    { nome: "Deyverson", posicao: "ATA", idade: 34, forca: 77 },
    { nome: "Eduardo Vargas", posicao: "ATA", idade: 36, forca: 75 },
    { nome: "Alan Kardec", posicao: "ATA", idade: 37, forca: 70 }
  ],
  int: [
    { nome: "Sergio Rochet", posicao: "GOL", idade: 32, forca: 80 },
    { nome: "Anthoni", posicao: "GOL", idade: 24, forca: 70 },
    { nome: "Vitão", posicao: "DEF", idade: 25, forca: 79 },
    { nome: "Gabriel Mercado", posicao: "DEF", idade: 38, forca: 75 },
    { nome: "Alexandro Bernabei", posicao: "DEF", idade: 25, forca: 77 },
    { nome: "Agustín Rogel", posicao: "DEF", idade: 28, forca: 75 },
    { nome: "Bruno Gomes", posicao: "DEF", idade: 24, forca: 75 },
    { nome: "Renê", posicao: "DEF", idade: 33, forca: 74 },
    { nome: "Nathan", posicao: "DEF", idade: 24, forca: 72 },
    { nome: "Alan Patrick", posicao: "MEI", idade: 34, forca: 81 },
    { nome: "Thiago Maia", posicao: "MEI", idade: 28, forca: 78 },
    { nome: "Fernando", posicao: "MEI", idade: 38, forca: 77 },
    { nome: "Bruno Henrique", posicao: "MEI", idade: 36, forca: 75 },
    { nome: "Bruno Tabata", posicao: "MEI", idade: 28, forca: 76 },
    { nome: "Gabriel Carvalho", posicao: "MEI", idade: 18, forca: 72 },
    { nome: "Wesley", posicao: "MEI", idade: 26, forca: 75 },
    { nome: "Rafael Borré", posicao: "ATA", idade: 30, forca: 81 },
    { nome: "Enner Valencia", posicao: "ATA", idade: 36, forca: 79 },
    { nome: "Lucas Alario", posicao: "ATA", idade: 33, forca: 76 },
    { nome: "Wanderson", posicao: "ATA", idade: 31, forca: 76 },
    { nome: "Lucca", posicao: "ATA", idade: 22, forca: 71 }
  ],
  gre: [
    { nome: "Agustín Marchesín", posicao: "GOL", idade: 37, forca: 77 },
    { nome: "Rafael Cabral", posicao: "GOL", idade: 35, forca: 72 },
    { nome: "Walter Kannemann", posicao: "DEF", idade: 34, forca: 78 },
    { nome: "Jemerson", posicao: "DEF", idade: 33, forca: 77 },
    { nome: "Rodrigo Ely", posicao: "DEF", idade: 32, forca: 76 },
    { nome: "Reinaldo", posicao: "DEF", idade: 36, forca: 76 },
    { nome: "João Pedro", posicao: "DEF", idade: 29, forca: 75 },
    { nome: "Gustavo Martins", posicao: "DEF", idade: 23, forca: 73 },
    { nome: "Mayk", posicao: "DEF", idade: 26, forca: 71 },
    { nome: "Franco Cristaldo", posicao: "MEI", idade: 29, forca: 79 },
    { nome: "Mathías Villasanti", posicao: "MEI", idade: 29, forca: 79 },
    { nome: "Miguel Monsalve", posicao: "MEI", idade: 22, forca: 75 },
    { nome: "Edenilson", posicao: "MEI", idade: 36, forca: 74 },
    { nome: "Pepê", posicao: "MEI", idade: 28, forca: 75 },
    { nome: "Dodi", posicao: "MEI", idade: 29, forca: 74 },
    { nome: "Ronald", posicao: "MEI", idade: 23, forca: 70 },
    { nome: "Martin Braithwaite", posicao: "ATA", idade: 34, forca: 80 },
    { nome: "Yeferson Soteldo", posicao: "ATA", idade: 28, forca: 80 },
    { nome: "Diego Costa", posicao: "ATA", idade: 37, forca: 77 },
    { nome: "Cristian Pavón", posicao: "ATA", idade: 30, forca: 76 },
    { nome: "Nathan Fernandes", posicao: "ATA", idade: 20, forca: 71 }
  ],
  flu: [
    { nome: "Fábio", posicao: "GOL", idade: 45, forca: 78 },
    { nome: "Felipe Alves", posicao: "GOL", idade: 37, forca: 69 },
    { nome: "Thiago Silva", posicao: "DEF", idade: 41, forca: 81 },
    { nome: "Thiago Santos", posicao: "DEF", idade: 36, forca: 74 },
    { nome: "Samuel Xavier", posicao: "DEF", idade: 35, forca: 75 },
    { nome: "Guga", posicao: "DEF", idade: 27, forca: 74 },
    { nome: "Diogo Barbosa", posicao: "DEF", idade: 33, forca: 73 },
    { nome: "Ignácio", posicao: "DEF", idade: 29, forca: 75 },
    { nome: "Manoel", posicao: "DEF", idade: 36, forca: 72 },
    { nome: "Ganso", posicao: "MEI", idade: 36, forca: 79 },
    { nome: "Jhon Arias", posicao: "MEI", idade: 28, forca: 82 },
    { nome: "Martinelli", posicao: "MEI", idade: 24, forca: 76 },
    { nome: "Facundo Bernal", posicao: "MEI", idade: 22, forca: 75 },
    { nome: "Lima", posicao: "MEI", idade: 29, forca: 74 },
    { nome: "Nonato", posicao: "MEI", idade: 27, forca: 73 },
    { nome: "David Terans", posicao: "MEI", idade: 31, forca: 74 },
    { nome: "Germán Cano", posicao: "ATA", idade: 38, forca: 79 },
    { nome: "Keno", posicao: "ATA", idade: 36, forca: 76 },
    { nome: "Kauã Elias", posicao: "ATA", idade: 19, forca: 75 },
    { nome: "Kevin Serna", posicao: "ATA", idade: 28, forca: 75 },
    { nome: "Marquinhos", posicao: "ATA", idade: 22, forca: 73 }
  ],
  vas: [
    { nome: "Léo Jardim", posicao: "GOL", idade: 31, forca: 80 },
    { nome: "Keiller", posicao: "GOL", idade: 29, forca: 70 },
    { nome: "João Victor", posicao: "DEF", idade: 27, forca: 78 },
    { nome: "Maicon", posicao: "DEF", idade: 37, forca: 74 },
    { nome: "Lucas Piton", posicao: "DEF", idade: 25, forca: 77 },
    { nome: "Puma Rodríguez", posicao: "DEF", idade: 28, forca: 74 },
    { nome: "Léo", posicao: "DEF", idade: 29, forca: 73 },
    { nome: "Robert Rojas", posicao: "DEF", idade: 29, forca: 73 },
    { nome: "Victor Luis", posicao: "DEF", idade: 32, forca: 71 },
    { nome: "Dimitri Payet", posicao: "MEI", idade: 39, forca: 79 },
    { nome: "Philippe Coutinho", posicao: "MEI", idade: 33, forca: 77 },
    { nome: "Hugo Moura", posicao: "MEI", idade: 28, forca: 76 },
    { nome: "Mateus Carvalho", posicao: "MEI", idade: 22, forca: 74 },
    { nome: "Juan Sforza", posicao: "MEI", idade: 23, forca: 73 },
    { nome: "Jair", posicao: "MEI", idade: 31, forca: 74 },
    { nome: "Pablo Galdames", posicao: "MEI", idade: 29, forca: 71 },
    { nome: "Pablo Vegetti", posicao: "ATA", idade: 37, forca: 80 },
    { nome: "Adson", posicao: "ATA", idade: 25, forca: 75 },
    { nome: "David", posicao: "ATA", idade: 30, forca: 74 },
    { nome: "Emerson Rodríguez", posicao: "ATA", idade: 25, forca: 73 },
    { nome: "Rayan", posicao: "ATA", idade: 19, forca: 72 }
  ],
  cru: [
    { nome: "Cássio", posicao: "GOL", idade: 38, forca: 79 },
    { nome: "Anderson", posicao: "GOL", idade: 28, forca: 71 },
    { nome: "João Marcelo", posicao: "DEF", idade: 25, forca: 77 },
    { nome: "Zé Ivaldo", posicao: "DEF", idade: 29, forca: 76 },
    { nome: "Lucas Villalba", posicao: "DEF", idade: 31, forca: 75 },
    { nome: "William", posicao: "DEF", idade: 30, forca: 78 },
    { nome: "Marlon", posicao: "DEF", idade: 28, forca: 76 },
    { nome: "Kaiki", posicao: "DEF", idade: 23, forca: 72 },
    { nome: "Jonathan Jesus", posicao: "DEF", idade: 21, forca: 70 },
    { nome: "Matheus Pereira", posicao: "MEI", idade: 27, forca: 82 },
    { nome: "Matheus Henrique", posicao: "MEI", idade: 28, forca: 78 },
    { nome: "Álvaro Barreal", posicao: "MEI", idade: 25, forca: 76 },
    { nome: "Lucas Romero", posicao: "MEI", idade: 31, forca: 75 },
    { nome: "Walace", posicao: "MEI", idade: 31, forca: 76 },
    { nome: "Lucas Silva", posicao: "MEI", idade: 32, forca: 74 },
    { nome: "Japa", posicao: "MEI", idade: 22, forca: 71 },
    { nome: "Kaio Jorge", posicao: "ATA", idade: 24, forca: 77 },
    { nome: "Gabriel Veron", posicao: "ATA", idade: 23, forca: 76 },
    { nome: "Lautaro Díaz", posicao: "ATA", idade: 27, forca: 75 },
    { nome: "Juan Dinenno", posicao: "ATA", idade: 31, forca: 75 },
    { nome: "Rafa Silva", posicao: "ATA", idade: 33, forca: 72 }
  ],
  cap: [
    { nome: "Mycael", posicao: "GOL", idade: 22, forca: 75 },
    { nome: "Léo Linck", posicao: "GOL", idade: 24, forca: 72 },
    { nome: "Thiago Heleno", posicao: "DEF", idade: 37, forca: 76 },
    { nome: "Kaique Rocha", posicao: "DEF", idade: 25, forca: 75 },
    { nome: "Lucas Esquivel", posicao: "DEF", idade: 24, forca: 75 },
    { nome: "Madson", posicao: "DEF", idade: 34, forca: 74 },
    { nome: "Mateo Gamarra", posicao: "DEF", idade: 25, forca: 73 },
    { nome: "Leo Godoy", posicao: "DEF", idade: 30, forca: 74 },
    { nome: "Fernando", posicao: "DEF", idade: 26, forca: 71 },
    { nome: "Fernandinho", posicao: "MEI", idade: 40, forca: 79 },
    { nome: "Bruno Zapelli", posicao: "MEI", idade: 23, forca: 76 },
    { nome: "Christian", posicao: "MEI", idade: 25, forca: 75 },
    { nome: "Erick", posicao: "MEI", idade: 28, forca: 75 },
    { nome: "Gabriel", posicao: "MEI", idade: 33, forca: 74 },
    { nome: "Felipinho", posicao: "MEI", idade: 24, forca: 72 },
    { nome: "João Cruz", posicao: "MEI", idade: 18, forca: 70 },
    { nome: "Gonzalo Mastriani", posicao: "ATA", idade: 32, forca: 77 },
    { nome: "Agustín Canobbio", posicao: "ATA", idade: 27, forca: 78 },
    { nome: "Pablo", posicao: "ATA", idade: 33, forca: 75 },
    { nome: "Julimar", posicao: "ATA", idade: 25, forca: 74 },
    { nome: "Tomás Cuello", posicao: "ATA", idade: 26, forca: 74 }
  ],
  bah: [
    { nome: "Marcos Felipe", posicao: "GOL", idade: 30, forca: 77 },
    { nome: "Adriel", posicao: "GOL", idade: 25, forca: 70 },
    { nome: "Gabriel Xavier", posicao: "DEF", idade: 24, forca: 77 },
    { nome: "Kanu", posicao: "DEF", idade: 28, forca: 75 },
    { nome: "Santiago Arias", posicao: "DEF", idade: 34, forca: 76 },
    { nome: "Luciano Juba", posicao: "DEF", idade: 26, forca: 75 },
    { nome: "Victor Cuesta", posicao: "DEF", idade: 37, forca: 74 },
    { nome: "Gilberto", posicao: "DEF", idade: 32, forca: 73 },
    { nome: "Cicinho", posicao: "DEF", idade: 37, forca: 70 },
    { nome: "Everton Ribeiro", posicao: "MEI", idade: 36, forca: 79 },
    { nome: "Cauly", posicao: "MEI", idade: 30, forca: 79 },
    { nome: "Jean Lucas", posicao: "MEI", idade: 27, forca: 77 },
    { nome: "Caio Alexandre", posicao: "MEI", idade: 26, forca: 77 },
    { nome: "Thaciano", posicao: "MEI", idade: 30, forca: 76 },
    { nome: "Rezende", posicao: "MEI", idade: 31, forca: 74 },
    { nome: "Yago Felipe", posicao: "MEI", idade: 31, forca: 72 },
    { nome: "Lucho Rodríguez", posicao: "ATA", idade: 22, forca: 78 },
    { nome: "Everaldo", posicao: "ATA", idade: 34, forca: 76 },
    { nome: "Biel", posicao: "ATA", idade: 24, forca: 75 },
    { nome: "Ademir", posicao: "ATA", idade: 31, forca: 74 },
    { nome: "Rafael Ratão", posicao: "ATA", idade: 30, forca: 73 }
  ],
  for: [
    { nome: "João Ricardo", posicao: "GOL", idade: 37, forca: 78 },
    { nome: "Maurício Kozlinski", posicao: "GOL", idade: 34, forca: 70 },
    { nome: "Benjamin Kuscevic", posicao: "DEF", idade: 29, forca: 76 },
    { nome: "Titi", posicao: "DEF", idade: 37, forca: 74 },
    { nome: "Emanuel Brítez", posicao: "DEF", idade: 33, forca: 76 },
    { nome: "Tinga", posicao: "DEF", idade: 32, forca: 76 },
    { nome: "Bruno Pacheco", posicao: "DEF", idade: 34, forca: 75 },
    { nome: "Tomás Cardona", posicao: "DEF", idade: 30, forca: 73 },
    { nome: "Eros Mancuso", posicao: "DEF", idade: 26, forca: 74 },
    { nome: "Hércules", posicao: "MEI", idade: 25, forca: 78 },
    { nome: "Tomás Pochettino", posicao: "MEI", idade: 29, forca: 77 },
    { nome: "Lucas Sasha", posicao: "MEI", idade: 36, forca: 74 },
    { nome: "Matheus Rossetto", posicao: "MEI", idade: 29, forca: 74 },
    { nome: "José Welison", posicao: "MEI", idade: 30, forca: 74 },
    { nome: "Calebe", posicao: "MEI", idade: 25, forca: 74 },
    { nome: "Kervin Andrade", posicao: "MEI", idade: 20, forca: 72 },
    { nome: "Juan Martín Lucero", posicao: "ATA", idade: 34, forca: 79 },
    { nome: "Yago Pikachu", posicao: "ATA", idade: 33, forca: 77 },
    { nome: "Breno Lopes", posicao: "ATA", idade: 30, forca: 75 },
    { nome: "Moisés", posicao: "ATA", idade: 29, forca: 75 },
    { nome: "Imanol Machuca", posicao: "ATA", idade: 26, forca: 74 }
  ],
  rbb: [
    { nome: "Cleiton", posicao: "GOL", idade: 28, forca: 77 },
    { nome: "Lucão", posicao: "GOL", idade: 25, forca: 69 },
    { nome: "Pedro Henrique", posicao: "DEF", idade: 30, forca: 75 },
    { nome: "Luan Cândido", posicao: "DEF", idade: 25, forca: 75 },
    { nome: "Juninho Capixaba", posicao: "DEF", idade: 29, forca: 76 },
    { nome: "Nathan Mendes", posicao: "DEF", idade: 23, forca: 74 },
    { nome: "Douglas Mendes", posicao: "DEF", idade: 21, forca: 72 },
    { nome: "Lucas Cunha", posicao: "DEF", idade: 28, forca: 73 },
    { nome: "Guilherme Lopes", posicao: "DEF", idade: 24, forca: 71 },
    { nome: "Lucas Evangelista", posicao: "MEI", idade: 30, forca: 77 },
    { nome: "Matheus Fernandes", posicao: "MEI", idade: 27, forca: 75 },
    { nome: "Jhon Jhon", posicao: "MEI", idade: 23, forca: 73 },
    { nome: "Eric Ramires", posicao: "MEI", idade: 25, forca: 74 },
    { nome: "Lincoln", posicao: "MEI", idade: 27, forca: 74 },
    { nome: "Gustavinho", posicao: "MEI", idade: 24, forca: 70 },
    { nome: "Jadsom", posicao: "MEI", idade: 24, forca: 73 },
    { nome: "Eduardo Sasha", posicao: "ATA", idade: 33, forca: 76 },
    { nome: "Thiago Borbas", posicao: "ATA", idade: 23, forca: 75 },
    { nome: "Henry Mosquera", posicao: "ATA", idade: 24, forca: 74 },
    { nome: "Vitinho", posicao: "ATA", idade: 27, forca: 74 },
    { nome: "Arthur Sousa", posicao: "ATA", idade: 22, forca: 70 }
  ],
  cui: [
    { nome: "Walter", posicao: "GOL", idade: 38, forca: 75 },
    { nome: "Mateus Pasinato", posicao: "GOL", idade: 33, forca: 69 },
    { nome: "Marllon", posicao: "DEF", idade: 33, forca: 74 },
    { nome: "Alan Empereur", posicao: "DEF", idade: 31, forca: 74 },
    { nome: "Matheus Alexandre", posicao: "DEF", idade: 27, forca: 73 },
    { nome: "Ramon", posicao: "DEF", idade: 24, forca: 72 },
    { nome: "Bruno Alves", posicao: "DEF", idade: 34, forca: 73 },
    { nome: "Gabriel Knesowitsch", posicao: "DEF", idade: 22, forca: 68 },
    { nome: "Allyson", posicao: "DEF", idade: 35, forca: 68 },
    { nome: "Denilson", posicao: "MEI", idade: 24, forca: 74 },
    { nome: "Lucas Mineiro", posicao: "MEI", idade: 29, forca: 72 },
    { nome: "Fernando Sobral", posicao: "MEI", idade: 31, forca: 73 },
    { nome: "Max", posicao: "MEI", idade: 24, forca: 70 },
    { nome: "Guilherme Madruga", posicao: "MEI", idade: 25, forca: 70 },
    { nome: "Filipe Augusto", posicao: "MEI", idade: 32, forca: 70 },
    { nome: "Lucas Fernandes", posicao: "MEI", idade: 28, forca: 71 },
    { nome: "Isidro Pitta", posicao: "ATA", idade: 26, forca: 77 },
    { nome: "Clayson", posicao: "ATA", idade: 30, forca: 74 },
    { nome: "Derik Lacerda", posicao: "ATA", idade: 26, forca: 73 },
    { nome: "Jonathan Cafu", posicao: "ATA", idade: 34, forca: 71 },
    { nome: "André Luís", posicao: "ATA", idade: 29, forca: 71 }
  ],
  vit: [
    { nome: "Lucas Arcanjo", posicao: "GOL", idade: 27, forca: 74 },
    { nome: "Muriel", posicao: "GOL", idade: 38, forca: 69 },
    { nome: "Wagner Leonardo", posicao: "DEF", idade: 26, forca: 76 },
    { nome: "Neris", posicao: "DEF", idade: 33, forca: 72 },
    { nome: "Lucas Esteves", posicao: "DEF", idade: 25, forca: 73 },
    { nome: "Willean Lepo", posicao: "DEF", idade: 29, forca: 72 },
    { nome: "Raúl Cáceres", posicao: "DEF", idade: 34, forca: 71 },
    { nome: "Edu", posicao: "DEF", idade: 25, forca: 68 },
    { nome: "Camutanga", posicao: "DEF", idade: 32, forca: 71 },
    { nome: "Matheusinho", posicao: "MEI", idade: 28, forca: 75 },
    { nome: "Willian Oliveira", posicao: "MEI", idade: 32, forca: 72 },
    { nome: "Luan Santos", posicao: "MEI", idade: 26, forca: 72 },
    { nome: "Machado", posicao: "MEI", idade: 29, forca: 71 },
    { nome: "Léo Naldi", posicao: "MEI", idade: 24, forca: 70 },
    { nome: "Jean Mota", posicao: "MEI", idade: 32, forca: 71 },
    { nome: "José Breno", posicao: "MEI", idade: 22, forca: 66 },
    { nome: "Alerrandro", posicao: "ATA", idade: 26, forca: 76 },
    { nome: "Osvaldo", posicao: "ATA", idade: 38, forca: 73 },
    { nome: "Janderson", posicao: "ATA", idade: 26, forca: 71 },
    { nome: "Everaldo", posicao: "ATA", idade: 31, forca: 70 },
    { nome: "Carlos Eduardo", posicao: "ATA", idade: 29, forca: 71 }
  ],
  cri: [
    { nome: "Gustavo", posicao: "GOL", idade: 33, forca: 73 },
    { nome: "Alisson", posicao: "GOL", idade: 29, forca: 68 },
    { nome: "Rodrigo", posicao: "DEF", idade: 30, forca: 73 },
    { nome: "Tobias Figueiredo", posicao: "DEF", idade: 32, forca: 72 },
    { nome: "Marcelo Hermes", posicao: "DEF", idade: 31, forca: 74 },
    { nome: "Claudinho", posicao: "DEF", idade: 25, forca: 72 },
    { nome: "Miguel Trauco", posicao: "DEF", idade: 33, forca: 73 },
    { nome: "Wilker Ángel", posicao: "DEF", idade: 32, forca: 72 },
    { nome: "Jonathan", posicao: "DEF", idade: 33, forca: 68 },
    { nome: "Fellipe Mateus", posicao: "MEI", idade: 35, forca: 74 },
    { nome: "Barreto", posicao: "MEI", idade: 30, forca: 72 },
    { nome: "Newton", posicao: "MEI", idade: 26, forca: 72 },
    { nome: "Marquinhos Gabriel", posicao: "MEI", idade: 35, forca: 72 },
    { nome: "Ronald", posicao: "MEI", idade: 28, forca: 70 },
    { nome: "Higor Meritão", posicao: "MEI", idade: 31, forca: 71 },
    { nome: "Eliomar", posicao: "MEI", idade: 23, forca: 66 },
    { nome: "Yannick Bolasie", posicao: "ATA", idade: 36, forca: 77 },
    { nome: "Arthur Caíke", posicao: "ATA", idade: 33, forca: 72 },
    { nome: "Felipe Vizeu", posicao: "ATA", idade: 28, forca: 72 },
    { nome: "Allano", posicao: "ATA", idade: 30, forca: 71 },
    { nome: "Eder", posicao: "ATA", idade: 39, forca: 71 }
  ],
  juv: [
    { nome: "Gabriel Vasconcelos", posicao: "GOL", idade: 33, forca: 74 },
    { nome: "Mateus Claus", posicao: "GOL", idade: 31, forca: 68 },
    { nome: "Danilo Boza", posicao: "DEF", idade: 27, forca: 74 },
    { nome: "Zé Marcos", posicao: "DEF", idade: 32, forca: 73 },
    { nome: "João Lucas", posicao: "DEF", idade: 27, forca: 73 },
    { nome: "Alan Ruschel", posicao: "DEF", idade: 36, forca: 73 },
    { nome: "Rodrigo Sam", posicao: "DEF", idade: 30, forca: 71 },
    { nome: "Lucas Freitas", posicao: "DEF", idade: 25, forca: 71 },
    { nome: "Yan Souto", posicao: "DEF", idade: 24, forca: 69 },
    { nome: "Jádson", posicao: "MEI", idade: 32, forca: 73 },
    { nome: "Jean Carlos", posicao: "MEI", idade: 33, forca: 74 },
    { nome: "Mandaca", posicao: "MEI", idade: 24, forca: 71 },
    { nome: "Nenê", posicao: "MEI", idade: 44, forca: 72 },
    { nome: "Dudu Vieira", posicao: "MEI", idade: 32, forca: 70 },
    { nome: "Oyama", posicao: "MEI", idade: 28, forca: 71 },
    { nome: "Ronaldo", posicao: "MEI", idade: 25, forca: 68 },
    { nome: "Lucas Barbosa", posicao: "ATA", idade: 24, forca: 76 },
    { nome: "Gilberto", posicao: "ATA", idade: 36, forca: 74 },
    { nome: "Erick Farias", posicao: "ATA", idade: 29, forca: 71 },
    { nome: "Marcelinho", posicao: "ATA", idade: 23, forca: 70 },
    { nome: "Ronie Carrillo", posicao: "ATA", idade: 29, forca: 71 }
  ],
  acg: [
    { nome: "Ronaldo", posicao: "GOL", idade: 29, forca: 73 },
    { nome: "Pedro Rangel", posicao: "GOL", idade: 25, forca: 69 },
    { nome: "Adriano Martins", posicao: "DEF", idade: 28, forca: 73 },
    { nome: "Alix Vinícius", posicao: "DEF", idade: 26, forca: 74 },
    { nome: "Guilherme Romão", posicao: "DEF", idade: 28, forca: 73 },
    { nome: "Maguinho", posicao: "DEF", idade: 34, forca: 71 },
    { nome: "Philipe Sampaio", posicao: "DEF", idade: 31, forca: 71 },
    { nome: "Luiz Felipe", posicao: "DEF", idade: 32, forca: 72 },
    { nome: "Marcão", posicao: "DEF", idade: 24, forca: 67 },
    { nome: "Shaylon", posicao: "MEI", idade: 28, forca: 76 },
    { nome: "Gabriel Baralhas", posicao: "MEI", idade: 27, forca: 74 },
    { nome: "Rhaldney", posicao: "MEI", idade: 27, forca: 72 },
    { nome: "Jorginho", posicao: "MEI", idade: 35, forca: 72 },
    { nome: "Roni", posicao: "MEI", idade: 26, forca: 71 },
    { nome: "Gustavo Campanharo", posicao: "MEI", idade: 33, forca: 71 },
    { nome: "Alejo Cruz", posicao: "MEI", idade: 25, forca: 71 },
    { nome: "Luiz Fernando", posicao: "ATA", idade: 29, forca: 77 },
    { nome: "Jan Hurtado", posicao: "ATA", idade: 25, forca: 72 },
    { nome: "Derek", posicao: "ATA", idade: 28, forca: 71 },
    { nome: "Emiliano Rodríguez", posicao: "ATA", idade: 22, forca: 70 },
    { nome: "Matías Lacava", posicao: "ATA", idade: 23, forca: 70 }
  ]
};
