export const botafogoRoster = [
  { name: "Léo Linck", position: "GOL" },
  { name: "Raul", position: "GOL" },
  { name: "Cristhian Loor", position: "GOL" },
  { name: "Nahuel Ferraresi", position: "ZAG" },
  { name: "Kaio", position: "ZAG" },
  { name: "Bastos", position: "ZAG" },
  { name: "Ythallo", position: "ZAG" },
  { name: "Anthony", position: "ZAG" },
  { name: "Alex Telles", position: "LE" },
  { name: "Marçal", position: "LE" },
  { name: "Jhoan Hernández", position: "LE" },
  { name: "Caio Roque", position: "LE" },
  { name: "Vitinho", position: "LD" },
  { name: "Mateo Ponte", position: "LD" },
  { name: "Newton", position: "VOL" },
  { name: "Patrick de Paula", position: "VOL" },
  { name: "Allan", position: "VOL" },
  { name: "Wallace Davi", position: "VOL" },
  { name: "Huguinho", position: "VOL" },
  { name: "Danilo", position: "MEI" },
  { name: "Cristian Medina", position: "MEI" },
  { name: "Edenilson", position: "MEI" },
  { name: "Santiago Rodríguez", position: "MEI" },
  { name: "Jordan Barrera", position: "MEI" },
  { name: "Álvaro Montoro", position: "PE" },
  { name: "Matheus Martins", position: "PE" },
  { name: "Diego Hernández", position: "PE" },
  { name: "Nathan Fernandes", position: "PD" },
  { name: "Júnior Santos", position: "PD" },
  { name: "Lucas Villalba", position: "PD" },
  { name: "Joaquín Correa", position: "CA" },
  { name: "Arthur Cabral", position: "CA" },
  { name: "Chris Ramos", position: "CA" },
  { name: "Matheus Nascimento", position: "CA" },
  { name: "Kadir Barría", position: "CA" },
  { name: "Elias Manoel", position: "CA" }
];
